In [1]:
from repif_ml.dvf_plus import process_dvf_plus_csv
import pandas as pd

In [ ]:
#df_investigation = pd.read_csv('../csv_data/dvf_plus/dvf_plus_d01.csv', sep="|")

In [ ]:
#df_investigation.head()

In [2]:
csv_dir_path = '../csv_data/dvf_plus'
df_house, df_apartment = process_dvf_plus_csv(csv_dir_path)

In [4]:
df_apartment.head()

,idmutation,datemut,anneemut,moismut,valeurfonc,sbati,nblocdep,l_codinsee,lon,lat
0,11990657,2023-11-20,2023,11,28100.0,20.0,1,01269,5.608898,46.148424
4,11994596,2023-07-05,2023,7,240000.0,50.0,2,01173,6.065180,46.339056
9,11992455,2023-07-31,2023,7,255000.0,125.0,2,01053,5.233280,46.206091
12,11995339,2023-12-28,2023,12,272480.0,84.0,2,01249,4.963811,45.825066
13,11996312,2023-12-18,2023,12,310000.0,70.0,3,01071,6.072722,46.314674

In [5]:
df_apartment.describe()

,idmutation,anneemut,moismut,valeurfonc,sbati,nblocdep,lon,lat
count,9.879350e+05,987935.000000,987935.000000,9.879350e+05,987935.000000,987935.000000,987624.000000,987624.000000
mean,1.394934e+07,2024.004654,6.588518,2.164795e+05,56.853458,1.243469,3.029773,45.829564
std,1.125507e+06,0.833221,3.388705,1.983715e+05,26.571550,0.957190,6.929369,6.379362
min,1.199036e+07,2023.000000,1.000000,1.010800e+04,11.000000,0.000000,-63.115048,-21.383545
25%,1.296655e+07,2023.000000,4.000000,1.080000e+05,38.000000,1.000000,1.815953,43.702035
50%,1.396840e+07,2024.000000,7.000000,1.650000e+05,55.000000,1.000000,2.554831,46.229484
75%,1.494003e+07,2025.000000,9.000000,2.550000e+05,71.000000,2.000000,5.376944,48.832838
max,1.585719e+07,2025.000000,12.000000,6.503600e+06,543.000000,97.000000,55.824254,83.517767

In [6]:
df_apartment.shape

(987935, 10)

In [7]:
df_house.shape

(1247616, 10)