In [2]:
import numpy as np
import pandas as pd
from repif_ml.train_models import load_model, DEFAULT_FEATURES

In [3]:
model_apartment_dev = load_model("../models/apartment_dev_20260621_220900.joblib")
model_house_dev = load_model("../models/house_dev_20260621_220900.joblib")

In [4]:
# House
sample_house = pd.DataFrame([{
    "sbati": 265.0,              # living area m²
    "nblocdep": 2,              # nb of dependencies
    "lat": 43.61235229385763,
    "lon": 1.442024916080423,
    "l_codinsee": "31555",      # code INSEE
    "dpe_median": 4,            # DPE 1–7 (A=1 … G=7)
    "annee_construction": 1960, # year of construction
}])

# l_codinsee must be categorical for XGBoost
sample_house["l_codinsee"] = sample_house["l_codinsee"].astype("category")

log_price_house = model_house_dev.predict(sample_house[DEFAULT_FEATURES])[0]
price_eur_house = np.exp(log_price_house)

print(f"Estimated price house : {price_eur_house:,.0f} €")

Estimated price house : 936,567 €

In [5]:
importance_house = pd.Series(
    model_house_dev.feature_importances_,
    index=model_house_dev.feature_names_in_,
).sort_values(ascending=False)

pd_house = pd.DataFrame(importance_house, columns=["importance"])

pd_house["importance"] = pd_house["importance"] * 100

pd_house

                    importance
l_codinsee           39.924091
sbati                25.232008
lat                  13.676945
lon                  11.771416
nblocdep              4.737448
annee_construction    2.834168
dpe_median            1.823919

In [6]:
# Apartment
sample_apartment = pd.DataFrame([{
    "sbati": 102.55,              # living area m²
    "nblocdep": 2,              # nb of dependencies
    "lat": 43.60396440375128,
    "lon": 1.4457511537821262,
    "l_codinsee": "31555",      # code INSEE
    "dpe_median": 6,            # DPE 1–7 "A": 1,"B": 2,"C": 3,"D": 4,"E": 5,"F": 6,"G": 7,
    "annee_construction": 1960, # year of construction
}])

# l_codinsee must be categorical for XGBoost
sample_apartment["l_codinsee"] = sample_apartment["l_codinsee"].astype("category")

log_price_apartment = model_apartment_dev.predict(sample_apartment[DEFAULT_FEATURES])[0]
price_eur_apartment = np.exp(log_price_apartment)

print(f"Estimated price apartment : {price_eur_apartment:,.0f} €")

Estimated price apartment : 450,637 €

In [9]:
importance_apartment = pd.Series(
    model_apartment_dev.feature_importances_,
    index=model_apartment_dev.feature_names_in_,
).sort_values(ascending=False)

pd_apartment = pd.DataFrame(importance_apartment, columns=["importance"])

pd_apartment["importance"] = pd_apartment["importance"] * 100

pd_apartment

                    importance
l_codinsee           44.308060
sbati                26.738129
lat                  13.346110
lon                   6.582580
nblocdep              5.305322
annee_construction    2.505911
dpe_median            1.213899